spring:
 rabbitmq:
  host: localhost
  port: 5672
  username: sysadm
  password: sysadm
  
  
management:
   endpoints:
     web:
       exposure:
        include: "refresh"
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

who:
  am:
    i: application info!
    
    
public:
  info:
    type: default dependencies
