
eureka:
      client:
            serviceUrl:
                  defaultZone: http://localhost:8761/eureka/
      
who:
  am:
    i: this is Client-B Server
    a: modify123123123123123

my:
  hello: 으
