# Server Setting
server:
  port: 9001


# Spring Setting
spring:
  profiles:
    active: local
  application:
    name: HecateAuthIssue
  cloud:
    # config Server 설정.
    config:
      uri: http://222.122.205.220:9103
      profile: custom, hazelcast, legacy, message, score
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
#    livereload:
#      enabled: true
  # DataBase Setting
  datasource:
    initialization-mode: never
    url: jdbc:oracle:thin:@222.122.205.201:1521:UDB
    username: hecate
    password: hecate!1
    driver-class-name: oracle.jdbc.driver.OracleDriver

  # Thymeleaf Setting
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML

  rabbitmq:
    host: 222.122.205.220
    port: 5672
    username: sysadm
    password: sysadm 

# MyBatis Setting
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.uracle.hecate.auth.model
  configuration:
    default-scripting-language: com.uracle.hecate.auth.core.common.driver.EnhanceMybatisLanguageDriver

eureka:
  instance:
    #true : 서비스간 통신 시 hostname 보다 ip를 우선 사용, false : 우선 사용 안함.
    prefer-ip-address: true 
  client:
    service-url:
      #Eureka 서버 주소
      defaultZone: http://222.122.205.220:9102/eureka   

# Hystrix 설정
hystrix:
  command:
    productInfo:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    circuitBreaker:
        requestVolumeThreshold: 3   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true

# Loggin Setting
logging:
  level:
    root: info
    com.uracle.hecate.auth: info

    
